const LOGIN = 'LOGIN'
const REGISTER = 'REGISTER'
const PINRESET = 'PINRESET'
const TRANSFER = 'TRANSFER'
const TRANSACTIONHISTORY = 'TRANSACTIONHISTORY'
const TOGGLEBALANCE = 'TOGGLEBALANCE'
const UPDATEUSER = 'UPDATEUSER'

export {
  LOGIN,
  REGISTER,
  PINRESET,
  TRANSFER,
  UPDATEUSER,
  TRANSACTIONHISTORY,
  TOGGLEBALANCE,
}
